export const SVG_NAMESPACE = 'http://www.w3.org/2000/svg'

export const sample_keys = [
  'accent',
  'bass_drum',
  'snare_drum',
  'low_tom',
  'mid_tom',
  'high_tom',
  'rim_shot',
  'hand_clap',
  'low_conga',
  'mid_conga',
  'high_conga',
  'claves',
  'maracas',
  'cowbell',
  'cymbal',
  'open_hat',
  'closed_hat',
];

export const sample_names = {
  accent     : 'Accent',
  bass_drum  : 'Bass Drum',
  snare_drum : 'Snare Drum',
  low_tom    : 'Low Tom',
  mid_tom    : 'Mid Tom',
  high_tom   : 'High Tom',
  rim_shot   : 'Rim Shot',
  hand_clap  : 'Hand Clap',
  low_conga  : 'Low Conga',
  mid_conga  : 'Mid Conga',
  high_conga : 'High Conga',
  claves     : 'Claves',
  maracas    : 'Maracas',
  cowbell    : 'Cowbell',
  cymbal     : 'Cymbal',
  open_hat   : 'Open Hat',
  closed_hat : 'Closed Hat',
};

export const sample_urls = {
  accent     : 'https://bluesaltlabs.github.io/resources/samples/808/accent.wav',
  bass_drum  : 'https://bluesaltlabs.github.io/resources/samples/808/bass_drum.wav',
  snare_drum : 'https://bluesaltlabs.github.io/resources/samples/808/snare_drum.wav',
  low_tom    : 'https://bluesaltlabs.github.io/resources/samples/808/low_tom.wav',
  mid_tom    : 'https://bluesaltlabs.github.io/resources/samples/808/mid_tom.wav',
  high_tom   : 'https://bluesaltlabs.github.io/resources/samples/808/high_tom.wav',
  rim_shot   : 'https://bluesaltlabs.github.io/resources/samples/808/rim_shot.wav',
  hand_clap  : 'https://bluesaltlabs.github.io/resources/samples/808/hand_clap.wav',
  low_conga  : 'https://bluesaltlabs.github.io/resources/samples/808/low_conga.wav',
  mid_conga  : 'https://bluesaltlabs.github.io/resources/samples/808/mid_conga.wav',
  high_conga : 'https://bluesaltlabs.github.io/resources/samples/808/high_conga.wav',
  claves     : 'https://bluesaltlabs.github.io/resources/samples/808/claves.wav',
  maracas    : 'https://bluesaltlabs.github.io/resources/samples/808/maracas.wav',
  cowbell    : 'https://bluesaltlabs.github.io/resources/samples/808/cowbell.wav',
  cymbal     : 'https://bluesaltlabs.github.io/resources/samples/808/cymbal.wav',
  open_hat   : 'https://bluesaltlabs.github.io/resources/samples/808/open_hat.wav',
  closed_hat : 'https://bluesaltlabs.github.io/resources/samples/808/closed_hat.wav',
};
